### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by nicfit** [redshodan/unsonic#3]
My commit was to fix this, it doesn't.
Although the files are included in the dist now.
```
Unsonic-sqlite      | General error:
Unsonic-sqlite      | Traceback (most recent call last):
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/mishmash/__main__.py", line 46, in main
Unsonic-sqlite      |     retval = args.command_func(args, args.config) or 0
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/mishmash/core.py", line 16, in run
Unsonic-sqlite      |     retval = super().run(args)
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/nicfit/command.py", line 49, in run
Unsonic-sqlite      |     return self._run()
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/unsonic/commands/sync.py", line 13, in newrun
Unsonic-sqlite      |     initAlembic()
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/unsonic/models.py", line 313, in initAlembic
Unsonic-sqlite      |     command.upgrade(alembic_cfg, "head")
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
Unsonic-sqlite      |     script.run_env()
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/alembic/script/base.py", line 416, in run_env
Unsonic-sqlite      |     util.load_python_file(self.dir, 'env.py')
Unsonic-sqlite      |   File "/unsonic/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 99, in load_python_file
Unsonic-sqlite      |     raise ImportError("Can't find Python file %s" % path)
Unsonic-sqlite      | ImportError: Can't find Python file /unsonic/lib/python3.6/site-packages/unsonic/alembic/env.py
```

**Comment by nicfit** [comment]
Nope, the commit does fix this. Docker was out out date.
