### ISSUE TITLE
Can't serve with v0.1.1

### ISSUE THREAD

**Issue by benschumacher** [redshodan/unsonic#53]
### Expected behavior

```
$ unsonic -c ... serve 
```

Runs the Unsonic API server.

### Actual behavior

Fails with exception:

```
$ bin/unsonic -c docker/config.ini serve
2018-01-23 12:52:30,396 ERROR [mishmash][MainThread] 'Serve' object has no attribute 'config'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mishmash/__main__.py", line 49, in main
    retval = args.command_func(args, args.config) or 0
  File "/Users/bschumac/src/repos/unsonic/unsonic/commands/serve.py", line 26, in run
    super()._run(args)
  File "/Users/bschumac/src/repos/unsonic/unsonic/commands/__init__.py", line 21, in _run
    initAlembic(self.config.get("mishmash", "sqlalchemy.url"))
AttributeError: 'Serve' object has no attribute 'config'
General error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mishmash/__main__.py", line 49, in main
    retval = args.command_func(args, args.config) or 0
  File "/Users/bschumac/src/repos/unsonic/unsonic/commands/serve.py", line 26, in run
    super()._run(args)
  File "/Users/bschumac/src/repos/unsonic/unsonic/commands/__init__.py", line 21, in _run
    initAlembic(self.config.get("mishmash", "sqlalchemy.url"))
AttributeError: 'Serve' object has no attribute 'config'
2018-01-23 12:52:30,397 DEBUG [unsonic][MainThread] Application._atexit
```

This appears to be related to change https://github.com/redshodan/unsonic/commit/ef3680acc07d9f24ddfb3ee51ef92cbd66f1ac9f.

### Steps to reproduce the behavior

Start Unsonic with `serve`.

**Comment by redshodan** [comment]
Fixed with v0.1.2
