### ISSUE TITLE
Traceback during `unsonic config`

### ISSUE THREAD

**Issue by nicfit** [redshodan/unsonic#55]
```
└> unsonic --version
unsonic (0.1.2, protocol: 0.1, subsonic protocol: 1.15.0) mishmash (0.3b5)

└> unsonic config
2018-01-27 19:02:41,878 DEBUG [unsonic][MainThread] Application._main: Namespace(VALUE=None, app=<unsonic.__main__.Unsonic object at 0x7fb074cd9dd8>, applyLoggingOpts=<function applyLoggingOpts at 0x7fb074014ae8>, command='config', command_func=<bound method Command.run of <unsonic.commands.config.Config object at 0x7fb06a4846d8>>, config=<unsonic.config.HereConfig object at 0x7fb06a499898>, config_show_default=False, db_url=None, debug_pdb=False, list=False, log_files=[], log_levels=[], set=None)
2018-01-27 19:02:41,878 DEBUG [mishmash.database][MainThread] Checking for database 'sqlite:////home/travis/devel/unsonic/venv/development.sqlite'
2018-01-27 19:02:41,881 INFO  [mishmash.database][MainThread] Creating database 'sqlite:////home/travis/devel/unsonic/venv/development.sqlite'
2018-01-27 19:02:41,882 ERROR [mishmash][MainThread] [Errno 2] No such file or directory: '/home/travis/devel/unsonic/venv/development.sqlite'
Traceback (most recent call last):
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/__main__.py", line 49, in main
    retval = args.command_func(args, args.config) or 0
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/core.py", line 22, in run
    self.db_conn) = database.init(self.config.db_url)
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/database.py", line 41, in init
    create_database(db_url, template="template0")
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 565, in create_database
    open(database, 'w').close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/devel/unsonic/venv/development.sqlite'
General error:
Traceback (most recent call last):
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/__main__.py", line 49, in main
    retval = args.command_func(args, args.config) or 0
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/core.py", line 22, in run
    self.db_conn) = database.init(self.config.db_url)
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/mishmash/database.py", line 41, in init
    create_database(db_url, template="template0")
  File "/home/travis/.virtualenvs/unsonic-0.1.x/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 565, in create_database
    open(database, 'w').close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/devel/unsonic/venv/development.sqlite'
```

**Comment by redshodan** [comment]
I think you haven't done a 'make' yet to build the venv. If you don't spec a config file, it'll look at a few places like /etc/unsonic.ini, also just to make dev easier, it'll look at `pwd`/unsonic/etc/development.ini, which is the config it found for this run. That config says `pwd`/venv/development.sqlite for the db, and I bet that venv dir isn't there because 'make build' wasn't run.

However, I should catch FileNotFoundError's and be mo' pretty about the bitching at the user.

**Comment by redshodan** [comment]
Did you run a system install of unsonic (via pip, or your own venv install) from the unsonic src tree? You couldn't have run the unsonic/bin/unsonic without doing a make build.
