### ISSUE TITLE
deluser traceback

### ISSUE THREAD

**Issue by nicfit** [redshodan/unsonic#6]
```
Traceback (most recent call last):
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: update or delete on table "un_users" violates foreign key constraint "fk_un_playcounts_user_id_un_users" on table "un_playcounts"
DETAIL:  Key (id)=(2) is still referenced from table "un_playcounts".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/unsonic/lib/python3.6/site-packages/mishmash/__main__.py", line 53, in main
    retval = args.command_func(args, args.config) or 0
  File "/unsonic/lib/python3.6/site-packages/mishmash/core.py", line 17, in run
    retval = super().run(args)
  File "/unsonic/lib/python3.6/site-packages/nicfit/command.py", line 55, in run
    return self._run()
  File "/unsonic/lib/python3.6/site-packages/unsonic/commands/deluser.py", line 22, in _run
    res.delete()
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3188, in delete
    delete_op.exec_()
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1179, in exec_
    self._do_exec()
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1363, in _do_exec
    mapper=self.mapper)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "un_users" violates foreign key constraint "fk_un_playcounts_user_id_un_users" on table "un_playcounts"
DETAIL:  Key (id)=(2) is still referenced from table "un_playcounts".
 [SQL: 'DELETE FROM un_users WHERE un_users.name = %(name_1)s'] [parameters: {'name_1': 'nicfit'}]
Traceback (most recent call last):
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/unsonic/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: update or delete on table "un_users" violates foreign key constraint "fk_un_playcounts_user_id_un_users" on table "un_playcounts"
DETAIL:  Key (id)=(2) is still referenced from table "un_playcounts".
```

**Comment by redshodan** [comment]
Fixed with merge of the db-fixup branch
